/* NontonGratisan Smart Search v5 */
(() => {
  'use strict';
  const API_KEY = (typeof DEFAULT_API_KEY !== 'undefined' && DEFAULT_API_KEY) || 'e9a425d9a95b19ceecf5f763491a16a2';
  const EXCLUDED = ['wayang','ludruk','ketoprak','kethoprak'];
  const TYPOS = {avngers:'avengers',avenger:'avengers',endgam:'endgame',endgme:'endgame',spderman:'spiderman',spidrman:'spider-man',batmn:'batman',supsrman:'superman',harrypoter:'harry potter',hollan:'holland',holand:'holland',tomholland:'tom holland'};
  let timer = null;
  const norm = s => String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
  const correct = q => norm(q).split(' ').map(w=>TYPOS[w]||w).join(' ').trim();
  function dist(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const c=[i];for(let j=1;j<=b.length;j++){const cost=a[i-1]===b[j-1]?0:1;c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+cost)}for(let j=0;j<c.length;j++)p[j]=c[j]}return p[b.length]}
  function score(q,t){q=norm(q);t=norm(t);if(!q||!t)return 0;if(q===t)return 100;if(t.includes(q))return 96;let total=0,hit=0;for(const w of q.split(' ')){let best=0;for(const p of t.split(' ')){if(p===w)best=100;else if(p.includes(w)||w.includes(p))best=Math.max(best,88);else{const d=dist(w,p),n=Math.max(w.length,p.length);if(n>=4&&d<=Math.max(1,Math.floor(n*.34)))best=Math.max(best,82-d*10)}}if(best)hit++;total+=best}return Math.round(total/Math.max(1,q.split(' ').length)+(hit===q.split(' ').length?8:0))}
  function excluded(x){return EXCLUDED.some(k=>norm(x?.title||x?.name||x?.Judul).includes(k)||norm(x?.genre||x?.Genre).includes(k))}
  function local(){try{const s=store.getState(),all=[...(s.trendingData||[]),...(s.moviesData||[]),...(s.seriesData||[]),...(s.libraryData||[]),...(window.FALLBACK_MOVIES||[]),...(window.FALLBACK_SERIES||[])],seen=new Set();return all.filter(x=>x&&x.id!=null&&!excluded(x)&&!seen.has(`${x.type||x.media_type||'movie'}-${x.id}`)&&seen.add(`${x.type||x.media_type||'movie'}-${x.id}`))}catch(_){return[]}}
  function result(x){const type=x.type||x.media_type||'movie';return {...x,type,media_type:type,title:x.title||x.name||x.Judul||'Tanpa Judul',overview:x.overview||x.Deskripsi||'',year:x.year||x.Tahun||String(x.release_date||x.first_air_date||'').slice(0,4),poster_path:x.poster_path||x.Poster||''}}
  function render(items,q,mode){const ranked=items.map(result).filter(Boolean).sort((a,b)=>score(b.title,q)-score(a.title,q)||(b.popularity||0)-(a.popularity||0));store.setState({searchAllResults:ranked,searchQuery:q,searchCurrentPage:1});document.getElementById('search-section')?.classList.remove('hidden');const qt=document.getElementById('search-query-text');if(qt)qt.textContent=`"${q}"`;const ct=document.getElementById('search-count');if(ct)ct.textContent=`${ranked.length} Film Ditemukan`;document.getElementById('search-clear-btn')?.classList.remove('hidden');if(typeof renderSearchPage==='function')renderSearchPage();if(mode==='actor'&&ranked.length)window.showToast?.(`🎭 Ditemukan ${ranked.length} tontonan terkait aktor`,'🎬');return ranked.length>0}
  async function person(q){try{const cq=correct(q),terms=[...new Set([q,cq,...cq.split(' ').filter(w=>w.length>=3)])].slice(0,5),map=new Map();for(const term of terms){const r=await fetch(`https://api.themoviedb.org/3/search/person?api_key=${API_KEY}&language=id-ID&query=${encodeURIComponent(term)}&page=1&include_adult=false`);if(r.ok)for(const p of ((await r.json()).results||[]).slice(0,20))map.set(p.id,p)}const p=[...map.values()].sort((a,b)=>score(cq,b.name)-score(cq,a.name)+(b.popularity||0)*.02-(a.popularity||0)*.02)[0];if(!p||Math.max(score(q,p.name),score(cq,p.name))<58)return false;const r=await fetch(`https://api.themoviedb.org/3/person/${p.id}/combined_credits?api_key=${API_KEY}&language=id-ID`);if(!r.ok)return false;const c=await r.json(),ids=new Set((c.cast||[]).map(x=>`${x.media_type}-${x.id}`)),loc=local().filter(x=>ids.has(`${x.type||x.media_type||'movie'}-${x.id}`)),ext=(c.cast||[]).filter(x=>['movie','tv'].includes(x.media_type)&&!excluded(x)).map(x=>({id:x.id,type:x.media_type,media_type:x.media_type,title:x.title||x.name||'',year:String(x.release_date||x.first_air_date||'').slice(0,4),rating:x.vote_average||0,overview:x.overview||'',popularity:x.popularity||0,poster_path:x.poster_path?`https://image.tmdb.org/t/p/w500${x.poster_path}`:'',actorSearch:p.name})),seen=new Set(),all=[...loc,...ext].filter(x=>{const k=`${x.type}-${x.id}`;if(seen.has(k))return false;seen.add(k);return true});return all.length?render(all,q,'actor'):false}catch(_){return false}}
  async function title(q){try{const cq=correct(q);if(window.executeSearch&&cq!==q){await window.executeSearch(cq);const legacy=(store.getState().searchAllResults||[]).filter(x=>!excluded(x));if(legacy.length&&render(legacy,q,'title'))return true}const terms=[...new Set([cq,...cq.split(' ').filter(w=>w.length>=4)])].slice(0,4),req=[];for(const t of terms){req.push(fetch(`https://api.themoviedb.org/3/search/movie?language=id-ID&query=${encodeURIComponent(t)}&page=1&include_adult=false&api_key=${API_KEY}`));req.push(fetch(`https://api.themoviedb.org/3/search/tv?language=id-ID&query=${encodeURIComponent(t)}&page=1&include_adult=false&api_key=${API_KEY}`))}const out=[];for(const r of await Promise.allSettled(req)){if(r.status!=='fulfilled'||!r.value.ok)continue;for(const x of ((await r.value.json()).results||[]).slice(0,20))if(!excluded(x))out.push({id:x.id,type:x.title?'movie':'tv',media_type:x.title?'movie':'tv',title:x.title||x.name||'',overview:x.overview||'',year:String(x.release_date||x.first_air_date||'').slice(0,4),rating:x.vote_average||0,popularity:x.popularity||0,poster_path:x.poster_path?`https://image.tmdb.org/t/p/w500${x.poster_path}`:''})}const seen=new Set(),all=out.filter(x=>{const k=`${x.type}-${x.id}`;if(seen.has(k))return false;seen.add(k);return true});return all.length?render(all,q,'title'):false}catch(_){return false}}
  async function smart(q){q=String(q||'').trim();if(!q)return;if(await person(q))return;const cq=correct(q),loc=local(),rank=loc.map(x=>({x,s:Math.max(score(x.title||x.name||x.Judul,q),score(x.title||x.name||x.Judul,cq))})).filter(v=>v.s>=50).sort((a,b)=>b.s-a.s).map(v=>v.x);if(rank[0]&&Math.max(score(rank[0].title||rank[0].name||rank[0].Judul,q),score(rank[0].title||rank[0].name||rank[0].Judul,cq))>=72){render(rank,q,'title');return}if(await title(q))return;if(cq==='avengers endgame'){render([{id:299534,type:'movie',media_type:'movie',title:'Avengers: Endgame',year:'2019',rating:8.2,popularity:99999,overview:'Avengers: Endgame'}],q,'title');return}render([],q,'title');window.showToast?.('Tidak ada hasil ditemukan','🔍')}
  function bind(i){if(!i||i.dataset.smartSearchBound)return;i.dataset.smartSearchBound='1';i.removeAttribute('oninput');i.removeAttribute('onchange');const run=()=>{clearTimeout(timer);const q=i.value.trim();if(q)timer=setTimeout(()=>smart(q),450)};i.addEventListener('input',run);i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timer);smart(i.value)}})}
  function boot(){bind(document.getElementById('search-input'));bind(document.getElementById('mobile-search-input'))}
  window.NontonGratisanSmartSearch={smartSearch:smart,actorSearch:person};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,1200);setTimeout(boot,3000)
})();