/* NontonGratisan Smart Search v8 — typo tolerant TMDB + local catalog */
(() => {
  'use strict';
  const EXCLUDED = ['wayang','ludruk','ketoprak','kethoprak'];
  const TYPOS = { avngers:'avengers', avenger:'avengers', endgam:'endgame', endgme:'endgame', spderman:'spiderman', spidrman:'spider-man', batmn:'batman', supsrman:'superman', harrypoter:'harry potter', hollan:'holland', holand:'holland', tomholland:'tom holland' };
  let timer;
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
  const correct=q=>norm(q).split(' ').map(w=>TYPOS[w]||w).join(' ').trim();
  const variants=q=>{const c=correct(q),w=c.split(' ').filter(Boolean),a=[q,c];if(w.length>1){a.push(...w);a.push(w.join(''));}return [...new Set(a.filter(Boolean))];};
  function dist(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<c.length;j++)p[j]=c[j];}return p[b.length];}
  function score(q,t){q=norm(q);t=norm(t);if(!q||!t)return 0;if(q===t)return 100;if(t.includes(q))return 96;const ws=q.split(' '),ps=t.split(' ');let total=0,hits=0;for(const w of ws){let best=0;for(const x of ps){if(x===w)best=100;else if(x.includes(w)||w.includes(x))best=Math.max(best,88);else{const d=dist(w,x),n=Math.max(w.length,x.length);if(n>=4&&d<=Math.max(1,Math.floor(n*.4)))best=Math.max(best,82-d*8);}}if(best)hits++;total+=best;}return Math.round(total/ws.length+(hits===ws.length?8:0));}
  const excluded=x=>{const a=norm(x?.title||x?.name||x?.Judul),b=norm(x?.genre||x?.Genre);return EXCLUDED.some(k=>a.includes(k)||b.includes(k));};
  const normalize=x=>{const type=x.media_type||x.type||(x.title?'movie':'tv');return {...x,id:x.id,type,media_type:type,title:x.title||x.name||x.Judul||'Tanpa Judul',overview:x.overview||x.Deskripsi||'',poster_path:x.poster_path||x.Poster||'',year:x.year||x.Tahun||String(x.release_date||x.first_air_date||'').slice(0,4),rating:x.rating||x.vote_average||0,popularity:Number(x.popularity||0),genre:x.genre||x.Genre||'',isLibraryItem:Boolean(x.isLibraryItem),source:x.source||(x.isLibraryItem?'PUSTAKA':'TMDB')};};
  const img=p=>!p?'https://placehold.co/500x750/18181b/ffffff?text=No+Poster':/^https?:\/\//i.test(p)?p:`https://image.tmdb.org/t/p/w500${p}`;
  function section(){let s=document.getElementById('smart-search-results');if(s)return s;const a=document.getElementById('movies-section')||document.querySelector('main section');if(!a?.parentNode)return null;s=document.createElement('section');s.id='smart-search-results';s.className='hidden space-y-4 sm:space-y-5 fade-in mb-6';s.innerHTML='<div class="flex items-center justify-between gap-3"><h2 class="text-base sm:text-xl font-bold text-white">🔍 Hasil Pencarian: <span id="smart-search-query" class="text-brand-500"></span></h2><button id="smart-search-clear" type="button" class="shrink-0 px-3 py-2 rounded-lg bg-zinc-800 text-xs text-zinc-300">Tutup</button></div><div id="smart-search-status" class="text-xs text-zinc-500"></div><div id="smart-search-grid" class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 sm:gap-4"></div>';a.parentNode.insertBefore(s,a);s.querySelector('#smart-search-clear').onclick=clear;return s;}
  function card(x){const t=String(x.title||'Tanpa Judul').replace(/[<>&"']/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[m]));const r=Number(x.rating||0).toFixed(1),type=x.type==='tv'?'Series':'Film';return `<article class="poster-card bg-zinc-900 rounded-xl overflow-hidden border border-zinc-800/80 cursor-pointer group" data-smart-id="${x.type}-${x.id}"><div class="relative aspect-[2/3] bg-zinc-950 overflow-hidden"><img src="${img(x.poster_path)}" alt="Poster ${t}" loading="lazy" class="w-full h-full object-cover group-hover:scale-105 transition-transform" onerror="this.src='https://placehold.co/500x750/18181b/ffffff?text=No+Poster'"><div class="absolute inset-x-0 bottom-0 p-2 bg-gradient-to-t from-black/90 to-transparent pt-8"><div class="text-[9px] text-white">⭐ ${r} • ${type}${x.year?' • '+x.year:''}</div></div></div><div class="p-2.5"><h3 class="text-xs font-bold text-white line-clamp-2">${t}</h3></div></article>`;}
  function openItem(x){const k=`${x.type}-${x.id}`;try{if(typeof mediaCache!=='undefined')mediaCache.set(k,x);}catch(_){}if(typeof openDetailPage==='function')return openDetailPage(x);if(typeof navigateToDetail==='function')return navigateToDetail(k);}
  function render(items,q,loading=false){const s=section();if(!s)return;s.classList.remove('hidden');s.querySelector('#smart-search-query').textContent=`"${q}"`;const st=s.querySelector('#smart-search-status'),g=s.querySelector('#smart-search-grid');if(loading){st.textContent='Mencari di katalog + TMDB...';g.innerHTML='<div class="col-span-full py-8 text-center text-sm text-zinc-500">🔎 Sedang mencari...</div>';return;}st.textContent=`${items.length} Film/Series ditemukan`;g.innerHTML=items.length?items.map(card).join(''):'<div class="col-span-full py-10 text-center text-sm text-zinc-500">Tidak ditemukan hasil. Coba judul lain atau periksa ejaan.</div>';g.querySelectorAll('[data-smart-id]').forEach((el,i)=>el.onclick=()=>openItem(items[i]));}
  async function tmdb(query){const all=[];for(const q of variants(query)){try{const u=`/api/tmdb?path=%2F3%2Fsearch%2Fmulti&include_adult=false&language=id-ID&page=1&query=${encodeURIComponent(q)}`;const r=await fetch(u,{headers:{accept:'application/json'}});if(!r.ok)continue;const d=await r.json();for(const x of d.results||[])if((x.media_type==='movie'||x.media_type==='tv')&&!excluded(x))all.push(normalize(x));}catch(_){} }return all;}
  function local(){try{const s=typeof store!=='undefined'&&store.getState?store.getState():{};const a=[...(s.libraryData||[]),...(s.moviesData||[]),...(s.seriesData||[]),...(s.trendingData||[])];const seen=new Set();return a.filter(x=>x&&x.id!=null&&!excluded(x)&&!seen.has(`${x.type||x.media_type||'movie'}-${x.id}`)&&(seen.add(`${x.type||x.media_type||'movie'}-${x.id}`),true)).map(normalize);}catch(_){return[];}}
  async function search(q){q=String(q||'').trim();if(!q)return clear();render([],q,true);const c=correct(q),l=local().map(x=>({x,s:Math.max(score(q,x.title),score(c,x.title),score(q,x.overview))})).filter(v=>v.s>=40).sort((a,b)=>b.s-a.s).map(v=>v.x),t=await tmdb(q);const merged=[...l,...t].map(normalize).filter(x=>x.id!=null&&!excluded(x)).map(x=>({x,s:Math.max(score(q,x.title),score(c,x.title))})).sort((a,b)=>b.s-a.s||b.x.popularity-a.x.popularity);const seen=new Set(),u=merged.filter(v=>{const k=`${v.x.type}-${v.x.id}`;if(seen.has(k))return false;seen.add(k);return true;}).map(v=>v.x);render(u.slice(0,60),q);try{if(typeof store!=='undefined'&&store.setState)store.setState({searchAllResults:u,searchQuery:q,searchCurrentPage:1});}catch(_){} }
  function clear(){document.getElementById('smart-search-results')?.classList.add('hidden');}
  function bind(i){if(!i||i.dataset.smartSearchV8)return;i.dataset.smartSearchV8='1';i.removeAttribute('oninput');i.removeAttribute('onchange');i.oninput=()=>{clearTimeout(timer);const q=i.value.trim();if(!q)return clear();timer=setTimeout(()=>search(q),350);};i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timer);search(i.value);}if(e.key==='Escape')clear();};}
  function boot(){bind(document.getElementById('search-input'));bind(document.getElementById('mobile-search-input'));}
  window.NontonGratisanSmartSearch={smartSearch:search,clear};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();[500,1500,3000,6000].forEach(ms=>setTimeout(boot,ms));
})();
