/* NontonGratisan Smart Search v6 — TMDB multi + local fuzzy search */
(() => {
  'use strict';
  const API_KEY = 'e9a425d9a95b19ceecf5f763491a16a2';
  const EXCLUDED = ['wayang','ludruk','ketoprak','kethoprak'];
  const TYPOS = {avngers:'avengers',avenger:'avengers',endgam:'endgame',endgme:'endgame',spderman:'spiderman',spidrman:'spider-man',batmn:'batman',supsrman:'superman',harrypoter:'harry potter',hollan:'holland',holand:'holland',tomholland:'tom holland'};
  let timer=null;
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
  const correct=q=>norm(q).split(' ').map(w=>TYPOS[w]||w).join(' ').trim();
  function dist(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<c.length;j++)p[j]=c[j]}return p[b.length]}
  function score(q,t){q=norm(q);t=norm(t);if(!q||!t)return 0;if(q===t)return 100;if(t.includes(q))return 96;const ws=q.split(' '),ps=t.split(' ');let total=0,hits=0;for(const w of ws){let best=0;for(const x of ps){if(x===w)best=100;else if(x.includes(w)||w.includes(x))best=Math.max(best,88);else{const d=dist(w,x),n=Math.max(w.length,x.length);if(n>=4&&d<=Math.max(1,Math.floor(n*.34)))best=Math.max(best,82-d*10)}}if(best)hits++;total+=best}return Math.round(total/ws.length+(hits===ws.length?8:0))}
  const excluded=x=>EXCLUDED.some(k=>norm(x?.title||x?.name||x?.Judul).includes(k)||norm(x?.genre||x?.Genre).includes(k));
  function localItems(){try{const s=store.getState(),all=[...(s.trendingData||[]),...(s.moviesData||[]),...(s.seriesData||[]),...(s.libraryData||[]),...(window.FALLBACK_MOVIES||[]),...(window.FALLBACK_SERIES||[])],seen=new Set();return all.filter(x=>x&&x.id!=null&&!excluded(x)&&!seen.has(`${x.type||x.media_type||'movie'}-${x.id}`)&&seen.add(`${x.type||x.media_type||'movie'}-${x.id}`))}catch(_){return[]}}
  const normalize=x=>{const type=x.media_type||x.type||(x.title?'movie':'tv');return {...x,type,media_type:type,title:x.title||x.name||x.Judul||'Tanpa Judul',overview:x.overview||x.Deskripsi||'',year:x.year||x.Tahun||String(x.release_date||x.first_air_date||'').slice(0,4),rating:x.rating||x.vote_average||0,poster_path:x.poster_path||x.Poster||'',popularity:x.popularity||0}};
  function render(items,q){const ranked=items.map(normalize).filter(x=>x.id!=null&&!excluded(x)).sort((a,b)=>score(q,b.title)-score(q,a.title)||(b.popularity||0)-(a.popularity||0)),seen=new Set(),unique=ranked.filter(x=>{const k=`${x.type}-${x.id}`;if(seen.has(k))return false;seen.add(k);return true});store.setState({searchAllResults:unique,searchQuery:q,searchCurrentPage:1});document.getElementById('search-section')?.classList.remove('hidden');const qt=document.getElementById('search-query-text');if(qt)qt.textContent=`"${q}"`;const ct=document.getElementById('search-count');if(ct)ct.textContent=`${unique.length} Film/Series Ditemukan`;document.getElementById('search-clear-btn')?.classList.remove('hidden');if(typeof renderSearchPage==='function')renderSearchPage();return unique}
  async function tmdbMulti(query){const all=[];for(const q of [...new Set([query,correct(query)])]){try{const r=await fetch(`https://api.themoviedb.org/3/search/multi?include_adult=false&language=id-ID&page=1&query=${encodeURIComponent(q)}&api_key=${API_KEY}`,{headers:{accept:'application/json'}});if(!r.ok)continue;const data=await r.json();for(const x of(data.results||[]))if(['movie','tv'].includes(x.media_type)&&!excluded(x))all.push(x)}catch(_){}}return all}
  async function personSearch(query){try{const cq=correct(query),r=await fetch(`https://api.themoviedb.org/3/search/person?include_adult=false&language=id-ID&page=1&query=${encodeURIComponent(cq)}&api_key=${API_KEY}`);if(!r.ok)return[];const people=(await r.json()).results||[],person=people.sort((a,b)=>score(cq,b.name)-score(cq,a.name)||(b.popularity||0)-(a.popularity||0))[0];if(!person||score(cq,person.name)<58)return[];const cr=await fetch(`https://api.themoviedb.org/3/person/${person.id}/combined_credits?language=id-ID&api_key=${API_KEY}`);if(!cr.ok)return[];const data=await cr.json();return(data.cast||[]).filter(x=>['movie','tv'].includes(x.media_type)&&!excluded(x)).map(x=>({...x,actorSearch:person.name}))}catch(_){return[]}}
  async function smart(query){query=String(query||'').trim();if(!query)return;const cq=correct(query),local=localItems(),localRank=local.map(x=>({x,s:Math.max(score(query,x.title||x.name||x.Judul),score(cq,x.title||x.name||x.Judul))})).filter(v=>v.s>=55).sort((a,b)=>b.s-a.s).map(v=>v.x);if(localRank[0]&&Math.max(score(query,localRank[0].title||localRank[0].name||localRank[0].Judul),score(cq,localRank[0].title||localRank[0].name||localRank[0].Judul))>=82){render(localRank,query);return}const multi=await tmdbMulti(query);if(multi.length){render([...localRank,...multi],query);return}const actor=await personSearch(query);if(actor.length){render([...localRank,...actor],query);return}render([],query);window.showToast?.('Tidak ada hasil ditemukan','🔍')}
  function bind(i){if(!i||i.dataset.smartSearchBound)return;i.dataset.smartSearchBound='1';i.removeAttribute('oninput');i.removeAttribute('onchange');const run=()=>{clearTimeout(timer);const q=i.value.trim();if(q)timer=setTimeout(()=>smart(q),450)};i.addEventListener('input',run);i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timer);smart(i.value)}})}
  function boot(){bind(document.getElementById('search-input'));bind(document.getElementById('mobile-search-input'))}
  window.NontonGratisanSmartSearch={smartSearch:smart};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();[1000,2500,5000].forEach(ms=>setTimeout(boot,ms));
})();
