function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function serviceAccount(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON belum disetel di Vercel');try{return JSON.parse(raw)}catch(e){throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON tidak valid')}}
async function googleAccessToken(){const sa=serviceAccount(),now=Math.floor(Date.now()/1000);const header=base64url(JSON.stringify({alg:'RS256',typ:'JWT'})),claim=base64url(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const signer=crypto.createSign('RSA-SHA256');signer.update(header+'.'+claim);signer.end();const assertion=header+'.'+claim+'.'+signer.sign(sa.private_key,'base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})}),j=await r.json();if(!r.ok)throw new Error(j.error_description||'Google OAuth gagal');return j.access_token}
async function sheetsGet(range){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA';const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range),{headers:{Authorization:'Bearer '+token}}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets read gagal');return j.values||[]}
async function sheetsAppend(values){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA',range=process.env.GOOGLE_SHEET_RANGE||'A:Z',url='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range)+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS&includeValuesInResponse=true';const r=await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:[values]})}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets append gagal');return j}
async function sheetsClear(range){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA';const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range)+':clear',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{}'}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets clear gagal');return j}
function headerKey(v){return String(v||'').trim().toLowerCase().replace(/[ _-]+/g,'')}
function mapRow(headers,data){const aliases={judul:['judul','title','name'],tipe:['tipe','type','jenis'],tahun:['tahun','year'],genre:['genre'],poster:['poster','posterpath','image','gambar','thumbnail'],deskripsi:['deskripsi','description','overview','sinopsis'],link:['link','player','url','embed','embedurl'],rating:['rating'],aktor:['aktor','cast','actors']};return headers.map(h=>{const k=headerKey(h);for(const [field,names] of Object.entries(aliases))if(names.includes(k))return data[field]??'';return ''})}
async function addToSheet(data){const values=await sheetsGet(process.env.GOOGLE_SHEET_RANGE||'1:1'),headers=values[0]||[];if(!headers.length)throw new Error('Header Google Sheet tidak ditemukan');const row=mapRow(headers,data);if(!row.some(Boolean))throw new Error('Kolom Google Sheet tidak cocok dengan field NOVA');return sheetsAppend(row)}
async function tmdbLookup(titleQuery){const key=process.env.TMDB_API_KEY;if(!key)throw new Error('TMDB_API_KEY belum disetel di Vercel');const u='https://api.themoviedb.org/3/search/multi?api_key='+encodeURIComponent(key)+'&language=id-ID&query='+encodeURIComponent(titleQuery)+'&include_adult=false',r=await fetch(u),j=await r.json();if(!r.ok)throw new Error(j.status_message||'TMDB gagal');const item=(j.results||[]).find(x=>x.media_type==='movie'||x.media_type==='tv');if(!item)throw new Error('Film/series tidak ditemukan di TMDB');const isTv=item.media_type==='tv';return{judul:isTv?(item.name||titleQuery):(item.title||titleQuery),tipe:isTv?'Series':'Film',tahun:String((isTv?item.first_air_date:item.release_date)||'').slice(0,4),genre:'',poster:item.poster_path?'https://image.tmdb.org/t/p/w780'+item.poster_path:'',deskripsi:item.overview||'',rating:item.vote_average?String(item.vote_average):'',aktor:''}}
async function searchAuthorizedEmbed(titleQuery){const apiKey=process.env.GOOGLE_CSE_API_KEY,cx=process.env.GOOGLE_CSE_ID,domains=String(process.env.AUTHORIZED_EMBED_DOMAINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!apiKey||!cx)return{url:'',results:[],note:'Pencarian embed belum aktif. Set GOOGLE_CSE_API_KEY, GOOGLE_CSE_ID, dan AUTHORIZED_EMBED_DOMAINS.'};if(!domains.length)return{url:'',results:[],note:'AUTHORIZED_EMBED_DOMAINS belum diisi. NOVA hanya mencari sumber embed yang Anda izinkan.'};const q=titleQuery+' official watch embed',u='https://www.googleapis.com/customsearch/v1?key='+encodeURIComponent(apiKey)+'&cx='+encodeURIComponent(cx)+'&q='+encodeURIComponent(q)+'&num=10&safe=active',r=await fetch(u),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Pencarian web gagal');const results=(j.items||[]).map(x=>({title:x.title,url:x.link,snippet:x.snippet||'',domain:x.displayLink||''})).filter(x=>{try{const host=new URL(x.url).hostname.toLowerCase();return domains.some(d=>host===d||host.endsWith('.'+d))}catch{return false}}).slice(0,5);return{url:results[0]?.url||'',results,note:results.length?'Sumber dipilih dari domain yang Anda izinkan.':'Tidak ditemukan sumber dari domain yang Anda izinkan.'}}
async function prepareVideo(titleQuery){if(!titleQuery)throw new Error('Judul film wajib diisi');const meta=await tmdbLookup(titleQuery),embed=await searchAuthorizedEmbed(meta.judul);return{data:{...meta,link:embed.url},embedResults:embed.results,note:embed.note}}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row)}if(!rows.length)return[];const h=rows.shift().map(v=>v.trim().replace(/^\uFEFF/,'').toLowerCase());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])));}
function title(x){return x.judul||x.title||x.name||'Tanpa Judul'} function isSeries(x){const t=((x.tipe||x.type||x.jenis||'')+' '+title(x)+' '+(x.genre||'')).toLowerCase();return /series|tv|serial|drakor|k-drama|episode|season/.test(t)} function player(x){return String(x.link||x.player||x.url||'').trim()} function stats(items){const films=items.filter(x=>!isSeries(x)).length;return{total:items.length,films,series:items.length-films,noPlayer:items.filter(x=>!/^https?:\/\//i.test(player(x))).length}}
function searchItems(items,q){const terms=q.toLowerCase().split(/\s+/).filter(Boolean);return items.filter(x=>{const s=JSON.stringify(x).toLowerCase();return terms.every(t=>s.includes(t))}).slice(0,40)}
function audit(items){const missing={title:0,poster:0,genre:0,year:0,player:0},seen=new Map(),duplicates=[];for(const x of items){const t=title(x).trim();if(!t||t==='Tanpa Judul')missing.title++;if(!(x.poster||x.poster_path||x.image||x.gambar||x.thumbnail))missing.poster++;if(!String(x.genre??'').trim())missing.genre++;if(!String(x.tahun??x.year??'').trim())missing.year++;if(!/^https?:\/\//i.test(player(x)))missing.player++;const k=t.toLowerCase();if(k&&k!=='tanpa judul'){if(seen.has(k))duplicates.push({title:t,count:seen.get(k)+1});seen.set(k,(seen.get(k)||0)+1)}}return{...stats(items),missing,duplicates:duplicates.slice(0,30),duplicateGroups:duplicates.length}}
function suggestions(items){const a=audit(items),s=[];if(a.missing.title)s.push({priority:'tinggi',issue:'Judul kosong',count:a.missing.title,action:'Lengkapi judul dari sumber katalog yang sah sebelum dipublikasikan.'});if(a.missing.poster)s.push({priority:'sedang',issue:'Poster kosong',count:a.missing.poster,action:'Lengkapi poster menggunakan aset yang penggunaannya berizin.'});if(a.missing.genre)s.push({priority:'sedang',issue:'Genre kosong',count:a.missing.genre,action:'Lengkapi genre berdasarkan metadata dari sumber yang sah.'});if(a.missing.year)s.push({priority:'sedang',issue:'Tahun kosong',count:a.missing.year,action:'Lengkapi tahun rilis berdasarkan sumber metadata yang sah.'});if(a.missing.player)s.push({priority:'tinggi',issue:'Player/link kosong atau tidak valid',count:a.missing.player,action:'Periksa dan ganti hanya dengan URL sumber/player yang berizin.'});if(a.duplicateGroups)s.push({priority:'sedang',issue:'Judul duplikat',count:a.duplicateGroups,action:'Tinjau grup duplikat dan gabungkan/hapus hanya setelah konfirmasi admin.'});if(!s.length)s.push({priority:'info',issue:'Tidak ada masalah dasar terdeteksi',count:0,action:'Katalog lolos pemeriksaan dasar; tetap lakukan pengecekan berkala.'});return{...a,suggestions:s}}
async function catalog(){const r=await fetch(CATALOG_APPS_SCRIPT_URL,{cache:'no-store'});if(!r.ok)throw new Error('Katalog tidak bisa diakses: HTTP '+r.status);const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Apps Script katalog mengembalikan respons bukan JSON')}const rows=Array.isArray(data)?data:(Array.isArray(data.items)?data.items:(Array.isArray(data.data)?data.data:[]));if(!rows.length)throw new Error(data.error||'Katalog kosong atau format Apps Script tidak valid');return rows}
const CATALOG_APPS_SCRIPT_URL=process.env.CATALOG_APPS_SCRIPT_URL||'https://script.google.com/macros/s/AKfycbzXCYXUB7-aVkS6LAjHL8nlivXh3pAQ5IAX90hQ-Y7VKMFhdHMR4uhu3cecVh2-pr-roQ/exec';
function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function serviceAccount(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON belum disetel di Vercel');try{return JSON.parse(raw)}catch(e){throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON tidak valid')}}
async function googleAccessToken(){const sa=serviceAccount(),now=Math.floor(Date.now()/1000);const header=base64url(JSON.stringify({alg:'RS256',typ:'JWT'})),claim=base64url(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const signer=crypto.createSign('RSA-SHA256');signer.update(header+'.'+claim);signer.end();const assertion=header+'.'+claim+'.'+signer.sign(sa.private_key,'base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})}),j=await r.json();if(!r.ok)throw new Error(j.error_description||'Google OAuth gagal');return j.access_token}
async function sheetsGet(range){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA';const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range),{headers:{Authorization:'Bearer '+token}}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets read gagal');return j.values||[]}
async function sheetsAppend(values){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA',range=process.env.GOOGLE_SHEET_RANGE||'A:Z',url='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range)+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS&includeValuesInResponse=true';const r=await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:[values]})}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets append gagal');return j}
async function sheetsClear(range){const token=await googleAccessToken(),id=process.env.GOOGLE_SHEET_ID||'1LDf4YmqI_v4cl1v52qwCBZv5W-gP00mO8choo_R7YVA';const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+'/values/'+encodeURIComponent(range)+':clear',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{}'}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Google Sheets clear gagal');return j}
function headerKey(v){return String(v||'').trim().toLowerCase().replace(/[ _-]+/g,'')}
function mapRow(headers,data){const aliases={judul:['judul','title','name'],tipe:['tipe','type','jenis'],tahun:['tahun','year'],genre:['genre'],poster:['poster','posterpath','image','gambar','thumbnail'],deskripsi:['deskripsi','description','overview','sinopsis'],link:['link','player','url','embed','embedurl'],rating:['rating'],aktor:['aktor','cast','actors']};return headers.map(h=>{const k=headerKey(h);for(const [field,names] of Object.entries(aliases))if(names.includes(k))return data[field]??'';return ''})}
async function addToSheet(data){const values=await sheetsGet(process.env.GOOGLE_SHEET_RANGE||'1:1'),headers=values[0]||[];if(!headers.length)throw new Error('Header Google Sheet tidak ditemukan');const row=mapRow(headers,data);if(!row.some(Boolean))throw new Error('Kolom Google Sheet tidak cocok dengan field NOVA');return sheetsAppend(row)}
async function tmdbLookup(titleQuery){const key=process.env.TMDB_API_KEY;if(!key)throw new Error('TMDB_API_KEY belum disetel di Vercel');const u='https://api.themoviedb.org/3/search/multi?api_key='+encodeURIComponent(key)+'&language=id-ID&query='+encodeURIComponent(titleQuery)+'&include_adult=false',r=await fetch(u),j=await r.json();if(!r.ok)throw new Error(j.status_message||'TMDB gagal');const item=(j.results||[]).find(x=>x.media_type==='movie'||x.media_type==='tv');if(!item)throw new Error('Film/series tidak ditemukan di TMDB');const isTv=item.media_type==='tv';return{judul:isTv?(item.name||titleQuery):(item.title||titleQuery),tipe:isTv?'Series':'Film',tahun:String((isTv?item.first_air_date:item.release_date)||'').slice(0,4),genre:'',poster:item.poster_path?'https://image.tmdb.org/t/p/w780'+item.poster_path:'',deskripsi:item.overview||'',rating:item.vote_average?String(item.vote_average):'',aktor:''}}
async function searchAuthorizedEmbed(titleQuery){const apiKey=process.env.GOOGLE_CSE_API_KEY,cx=process.env.GOOGLE_CSE_ID,domains=String(process.env.AUTHORIZED_EMBED_DOMAINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!apiKey||!cx)return{url:'',results:[],note:'Pencarian embed belum aktif. Set GOOGLE_CSE_API_KEY, GOOGLE_CSE_ID, dan AUTHORIZED_EMBED_DOMAINS.'};if(!domains.length)return{url:'',results:[],note:'AUTHORIZED_EMBED_DOMAINS belum diisi. NOVA hanya mencari sumber embed yang Anda izinkan.'};const q=titleQuery+' official watch embed',u='https://www.googleapis.com/customsearch/v1?key='+encodeURIComponent(apiKey)+'&cx='+encodeURIComponent(cx)+'&q='+encodeURIComponent(q)+'&num=10&safe=active',r=await fetch(u),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Pencarian web gagal');const results=(j.items||[]).map(x=>({title:x.title,url:x.link,snippet:x.snippet||'',domain:x.displayLink||''})).filter(x=>{try{const host=new URL(x.url).hostname.toLowerCase();return domains.some(d=>host===d||host.endsWith('.'+d))}catch{return false}}).slice(0,5);return{url:results[0]?.url||'',results,note:results.length?'Sumber dipilih dari domain yang Anda izinkan.':'Tidak ditemukan sumber dari domain yang Anda izinkan.'}}
async function prepareVideo(titleQuery){if(!titleQuery)throw new Error('Judul film wajib diisi');const meta=await tmdbLookup(titleQuery),embed=await searchAuthorizedEmbed(meta.judul);return{data:{...meta,link:embed.url},embedResults:embed.results,note:embed.note}}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row)}if(!rows.length)return[];const h=rows.shift().map(v=>v.trim().replace(/^\uFEFF/,'').toLowerCase());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])));}
function title(x){return x.judul||x.title||x.name||'Tanpa Judul'} function isSeries(x){const t=((x.tipe||x.type||x.jenis||'')+' '+title(x)+' '+(x.genre||'')).toLowerCase();return /series|tv|serial|drakor|k-drama|episode|season/.test(t)} function player(x){return String(x.link||x.player||x.url||'').trim()} function stats(items){const films=items.filter(x=>!isSeries(x)).length;return{total:items.length,films,series:items.length-films,noPlayer:items.filter(x=>!/^https?:\/\//i.test(player(x))).length}}
function searchItems(items,q){const terms=q.toLowerCase().split(/\s+/).filter(Boolean);return items.filter(x=>{const s=JSON.stringify(x).toLowerCase();return terms.every(t=>s.includes(t))}).slice(0,40)}
function audit(items){const missing={title:0,poster:0,genre:0,year:0,player:0},seen=new Map(),duplicates=[];for(const x of items){const t=title(x).trim();if(!t||t==='Tanpa Judul')missing.title++;if(!(x.poster||x.poster_path||x.image||x.gambar||x.thumbnail))missing.poster++;if(!String(x.genre??'').trim())missing.genre++;if(!String(x.tahun??x.year??'').trim())missing.year++;if(!/^https?:\/\//i.test(player(x)))missing.player++;const k=t.toLowerCase();if(k&&k!=='tanpa judul'){if(seen.has(k))duplicates.push({title:t,count:seen.get(k)+1});seen.set(k,(seen.get(k)||0)+1)}}return{...stats(items),missing,duplicates:duplicates.slice(0,30),duplicateGroups:duplicates.length}}
function suggestions(items){const a=audit(items),s=[];if(a.missing.title)s.push({priority:'tinggi',issue:'Judul kosong',count:a.missing.title,action:'Lengkapi judul dari sumber katalog yang sah sebelum dipublikasikan.'});if(a.missing.poster)s.push({priority:'sedang',issue:'Poster kosong',count:a.missing.poster,action:'Lengkapi poster menggunakan aset yang penggunaannya berizin.'});if(a.missing.genre)s.push({priority:'sedang',issue:'Genre kosong',count:a.missing.genre,action:'Lengkapi genre berdasarkan metadata dari sumber yang sah.'});if(a.missing.year)s.push({priority:'sedang',issue:'Tahun kosong',count:a.missing.year,action:'Lengkapi tahun rilis berdasarkan sumber metadata yang sah.'});if(a.missing.player)s.push({priority:'tinggi',issue:'Player/link kosong atau tidak valid',count:a.missing.player,action:'Periksa dan ganti hanya dengan URL sumber/player yang berizin.'});if(a.duplicateGroups)s.push({priority:'sedang',issue:'Judul duplikat',count:a.duplicateGroups,action:'Tinjau grup duplikat dan gabungkan/hapus hanya setelah konfirmasi admin.'});if(!s.length)s.push({priority:'info',issue:'Tidak ada masalah dasar terdeteksi',count:0,action:'Katalog lolos pemeriksaan dasar; tetap lakukan pengecekan berkala.'});return{...a,suggestions:s}}
async function catalog(){const r=await fetch(CATALOG_APPS_SCRIPT_URL,{cache:'no-store'});if(!r.ok)throw new Error('Katalog tidak bisa diakses: HTTP '+r.status);const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Apps Script katalog mengembalikan respons bukan JSON')}const rows=Array.isArray(data)?data:(Array.isArray(data.items)?data.items:(Array.isArray(data.data)?data.data:[]));if(!rows.length)throw new Error(data.error||'Katalog kosong atau format Apps Script tidak valid');return rows}

function auth(req){if(String(process.env.NOVA_TEST_MODE||'').toLowerCase()==='true')return;const expected=process.env.NOVA_ADMIN_KEY;if(!expected)throw new Error('NOVA_ADMIN_KEY belum disetel di Vercel');if(!req.headers['x-nova-key']||req.headers['x-nova-key']!==expected){const e=new Error('Admin key salah atau belum diisi');e.status=401;throw e}}
async function generateCommentReply(comment,style='ramah'){
  if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY belum disetel di Vercel');
  const title=String(comment.title||'').trim(),name=String(comment.name||'Anonim').trim(),text=String(comment.text||'').trim();
  const input='Kamu adalah NOVA, admin komunitas situs katalog film/series. Buat DRAFT balasan komentar dalam Bahasa Indonesia. Balasan singkat 1-2 kalimat, ramah, natural, tidak mengaku sebagai manusia tertentu, tidak mengarang fakta film, tidak memberikan tautan streaming ilegal, dan jangan membahas data pribadi. Jika komentar berupa pertanyaan yang tidak bisa dijawab dari konteks, minta pengguna memberi detail. Judul: '+title+'\nNama: '+name+'\nKomentar: '+text+'\nGaya: '+style;
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model:MODEL,input,store:false})}),j=await r.json();
  if(!r.ok)throw new Error(j.error?.message||'OpenAI API gagal');
  let answer=j.output_text;if(!answer&&Array.isArray(j.output))answer=j.output.flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n');
  return {reply:(answer||'').trim()};
}
async function moderateComments(comments){
  if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY belum disetel di Vercel');
  const input='Kamu adalah NOVA, moderator komentar untuk situs katalog film/series. Klasifikasikan setiap komentar ke tepat satu kategori: Normal, Pertanyaan, Permintaan, Spam, Link mencurigakan, atau Kasar. Gunakan konteks komentar saja. Jangan menilai identitas atau karakter pribadi. Link mencurigakan berarti komentar berisi tautan/domain atau ajakan klik yang tampak tidak relevan, promosi, phishing, atau tidak jelas; jangan menyimpulkan ilegal hanya karena ada URL. Spam mencakup promosi berulang, iklan tidak relevan, flood, atau pola otomatis. Kasar untuk hinaan, pelecehan, ancaman, atau bahasa sangat ofensif. Pertanyaan adalah komentar yang meminta informasi. Permintaan adalah komentar yang meminta tindakan/konten. Normal adalah komentar wajar yang tidak termasuk kategori lain. Balas JSON array saja tanpa markdown dengan objek {commentId,category,reason,recommendedAction}. recommendedAction harus salah satu dari "biarkan","balas","tinjau","tandai spam".\nKOMENTAR:\n'+JSON.stringify(comments);
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model:MODEL,input,store:false})}),j=await r.json();
  if(!r.ok)throw new Error(j.error?.message||'OpenAI API gagal');
  let answer=j.output_text;if(!answer&&Array.isArray(j.output))answer=j.output.flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('');
  let parsed;try{parsed=JSON.parse((answer||'').trim())}catch{throw new Error('NOVA mengembalikan format moderasi yang tidak valid')}
  if(!Array.isArray(parsed))throw new Error('Format moderasi NOVA tidak valid');
  return parsed;
}
async function askAI(message,items){if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY belum disetel di Vercel');const matches=searchItems(items,message),s=stats(items),a=audit(items),input='Kamu adalah NOVA, asisten admin katalog film/series. Jawab Bahasa Indonesia, singkat dan praktis. Gunakan hanya data katalog. Jangan mengarang. Perubahan data harus dikonfirmasi admin. Jangan membantu salinan ilegal/tautan streaming tanpa izin.\nDATA:'+JSON.stringify({stats:s,audit:a,matches})+'\nPERTANYAAN:'+message;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model:MODEL,input,store:false})}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||'OpenAI API gagal');let answer=j.output_text;if(!answer&&Array.isArray(j.output))answer=j.output.flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n');return{answer:answer||'NOVA tidak menerima jawaban teks dari model.',stats:s,audit:a}}
module.exports=async function(req,res){try{if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});auth(req);const action=req.body?.action||'chat';if(action==='catalog_fix_preview'){const items=await catalog();const requested=Array.isArray(req.body?.rows)?req.body.rows.map(Number).filter(Number.isInteger):[];const a=audit(items);const selected=(requested.length?requested:items.map((_,i)=>i+2)).filter(n=>n>=2&&n<=items.length+1).map(n=>({row:n,title:title(items[n-2]),item:items[n-2],suggestion:a.missing}));return res.status(200).json({ok:true,rows:selected.slice(0,50),requiresConfirmation:true,note:'Preview saja. Tidak ada perubahan data.'})}
if(action==='catalog_delete_confirmed'){if(req.body?.confirm!==true)throw new Error('Konfirmasi admin diperlukan. Kirim confirm:true setelah preview.');const rows=Array.isArray(req.body?.rows)?req.body.rows.map(Number).filter(Number.isInteger):[];if(!rows.length||rows.length>20)throw new Error('rows harus berisi 1-20 nomor baris.');const headers=(await sheetsGet(process.env.GOOGLE_SHEET_RANGE||'1:1'))[0]||[];if(!headers.length)throw new Error('Header Google Sheet tidak ditemukan');const lastCol=String.fromCharCode(64+Math.min(headers.length,26));const results=[];for(const n of [...new Set(rows)].sort((a,b)=>b-a)){if(n<2)continue;const range='A'+n+':'+lastCol+n;const values=await sheetsGet(range);if(!values[0])continue;await sheetsClear(range);results.push({row:n,title:values[0][0]||'(tanpa judul)'});}return res.status(200).json({ok:true,deleted:results,warning:'Baris dikosongkan, bukan dihapus secara fisik. Periksa Sheet sebelum menghapus permanen.'})}
if(action==='ping')return res.status(200).json({ok:true});const items=await catalog();if(action==='catalog_summary')return res.status(200).json(stats(items));if(action==='catalog_audit')return res.status(200).json(audit(items));if(action==='catalog_suggestions')return res.status(200).json(suggestions(items));if(action==='prepare_video')return res.status(200).json(await prepareVideo(String(req.body?.title||'').trim()));if(action==='comment_reply_draft')return res.status(200).json({ok:true,...await generateCommentReply(req.body?.comment||{},String(req.body?.style||'ramah'))});if(action==='comment_moderate_batch'){const comments=Array.isArray(req.body?.comments)?req.body.comments.slice(0,30).map(x=>({commentId:String(x.commentId||''),mediaId:String(x.mediaId||''),title:String(x.title||''),name:String(x.name||'Anonim'),text:String(x.text||'')})).filter(x=>x.commentId||x.text):[];if(!comments.length)throw new Error('Komentar untuk moderasi kosong');return res.status(200).json({ok:true,results:await moderateComments(comments)});}if(action==='add_video'){const prepared=await prepareVideo(String(req.body?.title||'').trim()),selected=String(req.body?.embedUrl||prepared.data.link||'').trim();if(!selected)throw new Error('Embed berizin belum ditemukan. NOVA tidak akan menambahkan player kosong.');prepared.data.link=selected;return res.status(200).json({ok:true,data:prepared.data,embedResults:prepared.embedResults,saved:await addToSheet(prepared.data)})}if(action==='chat'){const message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({error:'Pesan kosong'});return res.status(200).json(await askAI(message,items))}return res.status(400).json({error:'Action tidak dikenal'})}catch(e){return res.status(e.status||500).json({error:e.message||'Server error'})}};